name: Delete Deployed Storybook (Pull Request)
on:
  pull_request:
    branches:
        - main
    types:
        - closed

env:
  PR_REPO_NAME: bpmn-react-pr-${{ github.event.pull_request.node_id }}

permissions:
  repository: write

jobs:
  delete-pr-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Delete repository for temporary deployment
        run: gh repo delete --yes alexanderskrock/{{ env.$PR_REPO_NAME }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}