name: Deploy Storybook (PR)

on:
  workflow_call:

env:
  ORG_NAME: alexanderskrock
  PR_REPO_NAME: bpmn-react-pr-${{ github.event.pull_request.node_id }}

jobs:
  create-pr-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Create new repository for temporary deployment
        run: gh repo create "${ORG_NAME}/${PR_REPO_NAME}"
        env:
          GH_TOKEN: ${GITHUB_TOKEN}

    
  update-pull-request-repository:
    needs:
      - create-pr-repository

    runs-on: ubuntu-latest
    environment: 
      name: pull-request
      url: https://alexanderskrock.github.io/{{ env.PR_REPO_NAME }}
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
        with:
          path: "repository"
      - run: npm ci
      - run: npm run build-storybook

      - uses: actions/checkout@v4
        with:
          repository: "${ORG_NAME}/${PR_REPO_NAME}"
          path: "pull-request-repository"    
      
      - name: Move files to pull request repository
        run: cp -r ./repository/storybook-static/* ./pull-request-repository/storybook-static/

      - name: Add deployment action
        run: |
          YAML=$(cat << EOF
          name: Deploy Storybook

          on:
            push:
              branches:
                - main

          # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
          permissions:
            contents: read
            pages: write
            id-token: write

          # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
          # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
          concurrency:
            group: "pages"
            cancel-in-progress: true

          jobs:      
              runs-on: ubuntu-latest
              environment:
                name: github-pages
                url: ${{ steps.deployment.outputs.page_url }}

              steps:
                - uses: actions/checkout@v4
                - uses: actions/setup-node@v4

                - uses: actions/configure-pages@v5
                - uses: actions/upload-pages-artifact@v3
                  with:
                    path: "./storybook-static"
                - id: deployment
                  uses: actions/deploy-pages@v4"
          EOF
          )
          echo ${YAML} >> ./pull-request-repository/.github/workflows/deploy.yml

      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - run: |
          cd ./pull-request-repository
          git add -A
          git commit -m $GITHUB_SHA
          git push -u origin main
