name: Test Storybook (Legacy Peer Dependencies)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        react-version:
          - ^16.14.0

    env:
      REACT_VERSION: ${{ matrix.react-version }}
      REACT_DOM_VERSION: ${{ matrix.react-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install legacy versions of peer dependencies
        run: npm i react-dom@${REACT_DOM_VERSION} react@${REACT_DOM_VERSION}

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build Storybook
        run: npm run build-storybook --quiet

      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && yarn test-storybook"
