name: Test Storybook (Legacy Peer Dependencies)

on:
  workflow_call:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        react-version:
          - ^16.14.0
          - ^17.0.0
        diagram-js-version:
          - ^13.2.0
          - ^14.1.0
        bpmn-js-version:
          - ^16.0.0
          - ^17.0.0
        exclude:
          - diagram-js-version: ^13.2.0
            bpmn-js-version: ^17.0.0
          - diagram-js-version: ^14.1.0
            bpmn-js-version: ^16.0.0

    env:
      REACT_VERSION: ${{ matrix.react-version }}
      REACT_DOM_VERSION: ${{ matrix.react-version }}
      DIAGRAM_JS_VERSION: ${{ matrix.diagram-js-version }}
      BPMN_JS_VERSION: ${{ matrix.bpmn-js-version }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install legacy versions of peer dependencies
        run: npm i react-dom@${REACT_DOM_VERSION} react@${REACT_DOM_VERSION} diagram-js@${DIAGRAM_JS_VERSION} bpmn-js@${BPMN_JS_VERSION}
      - run: npx playwright install --with-deps

      - run: npm run build-storybook --quiet

      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && npm run test-storybook"
