name: Test docs (Legacy BPMN IO Peer Dependencies)

on:
  workflow_call:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        includes:
          - diagram-js-version: ^13.2.0
            bpmn-js-version: ^16.0.0

    env:
      DIAGRAM_JS_VERSION: ${{ matrix.diagram-js-version }}
      BPMN_JS_VERSION: ${{ matrix.bpmn-js-version }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install legacy versions of peer dependencies
        run: npm i --no-package-lock --no-save diagram-js@${DIAGRAM_JS_VERSION} bpmn-js@${BPMN_JS_VERSION}
      - run: npx playwright install --with-deps

      - run: npm run build-docs --quiet

      - name: Serve docs and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server docs-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && npm run test-docs"
