name: Test docs (Legacy React Peer Dependencies)

on:
  workflow_call:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        react-version:
          - ^16.14.0
          - ^17.0.0

    env:
      REACT_VERSION: ${{ matrix.react-version }}
      REACT_DOM_VERSION: ${{ matrix.react-version }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - run: npm ci
      - name: Install legacy versions of peer dependencies
        run: npm i --no-package-lock --no-save react-dom@${REACT_DOM_VERSION} react@${REACT_VERSION}
      - run: npx playwright install --with-deps

      - run: npm run build-docs --quiet

      - name: Serve docs and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server docs-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && npm run test-docs"
