name: Verify pull requests

on:
  pull_request:
    branches:
      - main

jobs:
  verify-build:
    uses: ./.github/workflows/build-library.yml

  verify-storybook:
    uses: ./.github/workflows/test-storybook.yml

  verify-storybook-legacy-peerdeps:
    uses: ./.github/workflows/test-storybook-legacy-peerdeps.yml