name: Verify pull requests

on:
  pull_request:
    branches:
      - main

jobs:
  verify-lint:
    uses: ./.github/workflows/lint.yml

  verify-build:
    uses: ./.github/workflows/build-library.yml

  verify-docs:
    uses: ./.github/workflows/test-docs.yml

  verify-docs-legacy-peerdeps-react:
    uses: ./.github/workflows/test-docs-legacy-peerdeps-react.yml
  
  verify-docs-legacy-peerdeps-bpmn-io:
    uses: ./.github/workflows/test-docs-legacy-peerdeps-bpmn-io.yml